[workspace]
resolver = "2"
members = ["frida_core","frida_client","frida_server","frida_cli","frida_gui","frida_lib"]

[workspace.dependencies]
env_logger = "0.11.6"
log = "0.4.20"
tokio = { version = "1", features = ["full", "signal", "tracing"] }
tokio-util = "0.7.12"
serde_yaml = "0.9.34"
serde = "1.0"
serde_derive = "1.0.190"
base64 = "0.22.1"
rand = { version = "0.8.5", features = ["small_rng", "getrandom", "std_rng"] }
aes-gcm = "0.10.3"
x25519-dalek = { version = "2.0.1", features = ["getrandom", "static_secrets"] }