[package]
name = "frida_core"
version = "0.2.0"
edition = "2021"
license-file = "../LICENSE.md"
authors = ["alterwain"]
keywords = ["tun", "network", "tunnel", "vpn"]
categories = ["network-programming", "asynchronous"]
readme = "../README.md"
workspace = "../"

[lib]
crate-type = ["cdylib"]
path = "src/android.rs"

[[bin]]
name = "frida-cli"
path = "src/main.rs"

[[bin]]
name = "frida-gui"
path = "src/gui/mod.rs"

[dependencies]
clap = "2.33"
aes-gcm = "0.10.3"
tokio = { version = "1", features = ["full", "signal", "tracing"] }
tokio-util = "0.7.12"
serde = "1.0"
serde_derive = "1.0.190"
rand = { version = "0.8.5", features = ["small_rng", "getrandom", "std_rng"] }
block-modes = "0.8"
block-padding = "0.2"
generic-array = "0.14"
env_logger = "0.9"
log = "0.4.20"
futures = "0.3.30"
packet = "0.1.4"
async-channel = "2.3.1"
hex = "0.4"
serde_yaml = "0.9.34"
x25519-dalek = { version = "2.0.1", features = ["getrandom", "static_secrets"] }
base64 = "0.22.1"
chrono = "0.4.38"
console-subscriber = "0.4.0"
network-interface = "2.0.0"
tun = { version = "0.7.5", features = ["async"] }

[target.'cfg(target_os="windows")'.dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
dirs = "5.0.1"
tray-item = "0.10.0"

[target.'cfg(target_os="windows")'.build-dependencies]
embed-resource = "2.3"

[target.'cfg(target_os="android")'.dependencies]
jni = "^0.20"
robusta_jni = "0.2.2"
nonblock = "0.2.0"
log4rs = "1.3.0"