[package]
name = "frida_cli"
version = "0.2.0"
edition = "2021"
license-file = "../LICENSE.md"
authors = ["alterwain"]
keywords = ["tun", "network", "tunnel", "vpn"]
categories = ["network-programming", "asynchronous"]
readme = "../README.md"
workspace = "../"

[dependencies]
clap = "2.33"
serde_yaml = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
frida_core = { path = "../frida_core" }
frida_client = { path = "../frida_client" }
frida_server = { path = "../frida_server" }