[package]
name = "frida_client"
version = "0.2.0"
edition = "2021"
license-file = "../LICENSE.md"
authors = ["alterwain"]
keywords = ["tun", "network", "tunnel", "vpn"]
categories = ["network-programming", "asynchronous"]
readme = "../README.md"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
frida_core = { path = "../frida_core", package = "frida_core" }
regex = "1.11.1"
aes-gcm = { workspace = true }
x25519-dalek = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
base64 = { workspace = true }
log = { workspace = true }
rand = { workspace = true }