[package]
name = "frida_lib"
version = "0.2.0"
edition = "2021"
license-file = "../LICENSE.md"
authors = ["alterwain"]
keywords = ["tun", "network", "tunnel", "vpn"]
categories = ["network-programming", "asynchronous"]
readme = "../README.md"
workspace = "../"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
hex = "0.4"
log = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde_yaml = { workspace = true }
frida_core = { path = "../frida_core" }
frida_client = { path = "../frida_client" }

[target.'cfg(target_os="android")'.dependencies]
jni = "^0.20"
robusta_jni = "0.2.2"
nonblock = "0.2.0"
log4rs = "1.3.0"
